# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import random

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(283, 532)
        self.counter=0
        self.b1 = QtWidgets.QPushButton(Form,clicked=lambda :self.click(self.b1))
        self.b1.setGeometry(QtCore.QRect(10, 240, 61, 61))
        self.b1.setObjectName("b1")
        self.b2 = QtWidgets.QPushButton(Form,clicked= lambda :self.click(self.b2))
        self.b2.setGeometry(QtCore.QRect(80, 240, 61, 61))
        self.b2.setObjectName("b2")
        self.b3 = QtWidgets.QPushButton(Form,clicked= lambda :self.click(self.b3))
        self.b3.setGeometry(QtCore.QRect(150, 240, 61, 61))
        self.b3.setObjectName("b3")
        self.b4 = QtWidgets.QPushButton(Form,clicked= lambda :self.click(self.b4))
        self.b4.setGeometry(QtCore.QRect(10, 310, 61, 61))
        self.b4.setObjectName("b4")
        self.b5 = QtWidgets.QPushButton(Form,clicked= lambda :self.click(self.b5))
        self.b5.setGeometry(QtCore.QRect(80, 310, 61, 61))
        self.b5.setObjectName("b5")
        self.b6 = QtWidgets.QPushButton(Form,clicked= lambda :self.click(self.b6))
        self.b6.setGeometry(QtCore.QRect(150, 310, 61, 61))
        self.b6.setObjectName("b6")
        self.bx = QtWidgets.QPushButton(Form,clicked=lambda :self.click(self.bx))
        self.bx.setGeometry(QtCore.QRect(220, 290, 51, 41))
        self.bx.setObjectName("bx")
        self.bo = QtWidgets.QPushButton(Form,clicked= lambda :self.click(self.bo))
        self.bo.setGeometry(QtCore.QRect(220, 340, 51, 41))
        self.bo.setObjectName("bo")
        self.l1 = QtWidgets.QLabel(Form)
        self.l1.setGeometry(QtCore.QRect(10, 10, 81, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.l1.setFont(font)
        self.l1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.l1.setAutoFillBackground(True)
        self.l1.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.l1.setTextFormat(QtCore.Qt.AutoText)
        self.l1.setScaledContents(True)
        self.l1.setAlignment(QtCore.Qt.AlignCenter)
        self.l1.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard)
        self.l1.setObjectName("l1")
        self.l2 = QtWidgets.QLabel(Form)
        self.l2.setGeometry(QtCore.QRect(100, 10, 81, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.l2.setFont(font)
        self.l2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.l2.setAutoFillBackground(True)
        self.l2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.l2.setTextFormat(QtCore.Qt.AutoText)
        self.l2.setScaledContents(True)
        self.l2.setAlignment(QtCore.Qt.AlignCenter)
        self.l2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard)
        self.l2.setObjectName("l2")
        self.l3 = QtWidgets.QLabel(Form)
        self.l3.setGeometry(QtCore.QRect(190, 10, 81, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.l3.setFont(font)
        self.l3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.l3.setAutoFillBackground(True)
        self.l3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.l3.setTextFormat(QtCore.Qt.AutoText)
        self.l3.setScaledContents(True)
        self.l3.setAlignment(QtCore.Qt.AlignCenter)
        self.l3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard)
        self.l3.setObjectName("l3")
        self.l4 = QtWidgets.QLabel(Form)
        self.l4.setGeometry(QtCore.QRect(10, 80, 81, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.l4.setFont(font)
        self.l4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.l4.setAutoFillBackground(True)
        self.l4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.l4.setTextFormat(QtCore.Qt.AutoText)
        self.l4.setScaledContents(True)
        self.l4.setAlignment(QtCore.Qt.AlignCenter)
        self.l4.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard)
        self.l4.setObjectName("l4")
        self.l5 = QtWidgets.QLabel(Form)
        self.l5.setGeometry(QtCore.QRect(100, 80, 81, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.l5.setFont(font)
        self.l5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.l5.setAutoFillBackground(True)
        self.l5.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.l5.setTextFormat(QtCore.Qt.AutoText)
        self.l5.setScaledContents(True)
        self.l5.setAlignment(QtCore.Qt.AlignCenter)
        self.l5.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard)
        self.l5.setObjectName("l5")
        self.l6 = QtWidgets.QLabel(Form)
        self.l6.setGeometry(QtCore.QRect(190, 80, 81, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.l6.setFont(font)
        self.l6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.l6.setAutoFillBackground(True)
        self.l6.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.l6.setTextFormat(QtCore.Qt.AutoText)
        self.l6.setScaledContents(True)
        self.l6.setAlignment(QtCore.Qt.AlignCenter)
        self.l6.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard)
        self.l6.setObjectName("l6")
        self.l7 = QtWidgets.QLabel(Form)
        self.l7.setGeometry(QtCore.QRect(10, 150, 81, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.l7.setFont(font)
        self.l7.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.l7.setAutoFillBackground(True)
        self.l7.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.l7.setTextFormat(QtCore.Qt.AutoText)
        self.l7.setScaledContents(True)
        self.l7.setAlignment(QtCore.Qt.AlignCenter)
        self.l7.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard)
        self.l7.setObjectName("l7")
        self.l8 = QtWidgets.QLabel(Form)
        self.l8.setGeometry(QtCore.QRect(100, 150, 81, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.l8.setFont(font)
        self.l8.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.l8.setAutoFillBackground(True)
        self.l8.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.l8.setTextFormat(QtCore.Qt.AutoText)
        self.l8.setScaledContents(True)
        self.l8.setAlignment(QtCore.Qt.AlignCenter)
        self.l8.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard)
        self.l8.setObjectName("l8")
        self.l9 = QtWidgets.QLabel(Form)
        self.l9.setGeometry(QtCore.QRect(190, 150, 81, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.l9.setFont(font)
        self.l9.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.l9.setAutoFillBackground(True)
        self.l9.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.l9.setTextFormat(QtCore.Qt.AutoText)
        self.l9.setScaledContents(True)
        self.l9.setAlignment(QtCore.Qt.AlignCenter)
        self.l9.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard)
        self.l9.setObjectName("l9")
        self.b7 = QtWidgets.QPushButton(Form,clicked= lambda :self.click(self.b7))
        self.b7.setGeometry(QtCore.QRect(10, 380, 61, 61))
        self.b7.setObjectName("b7")
        self.b8 = QtWidgets.QPushButton(Form,clicked= lambda :self.click(self.b8))
        self.b8.setGeometry(QtCore.QRect(80, 380, 61, 61))
        self.b8.setObjectName("b8")
        self.b9 = QtWidgets.QPushButton(Form,clicked= lambda :self.click(self.b9))
        self.b9.setGeometry(QtCore.QRect(150, 380, 61, 61))
        self.b9.setObjectName("b9")
        self.bs = QtWidgets.QPushButton(Form,clicked= lambda :self.start_game())
        self.bs.setGeometry(QtCore.QRect(220, 400, 51, 41))
        self.bs.setObjectName("bs")
        self.ll = QtWidgets.QLabel(Form)
        self.ll.setGeometry(QtCore.QRect(40, 470, 181, 41))
        self.ll.setAutoFillBackground(True)
        self.ll.setFrameShape(QtWidgets.QFrame.Box)
        self.ll.setLineWidth(2)
        self.ll.setObjectName("ll")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "tic tac toe"))
        self.b1.setText(_translate("Form", "1"))
        self.b2.setText(_translate("Form", "2"))
        self.b3.setText(_translate("Form", "3"))
        self.b4.setText(_translate("Form", "4"))
        self.b5.setText(_translate("Form", "5"))
        self.b6.setText(_translate("Form", "6"))
        self.bx.setText(_translate("Form", "x"))
        self.bo.setText(_translate("Form", "o"))
        self.l1.setText(_translate("Form", "1"))
        self.l2.setText(_translate("Form", "2"))
        self.l3.setText(_translate("Form", "3"))
        self.l4.setText(_translate("Form", "4"))
        self.l5.setText(_translate("Form", "5"))
        self.l6.setText(_translate("Form", "6"))
        self.l7.setText(_translate("Form", "7"))
        self.l8.setText(_translate("Form", "8"))
        self.l9.setText(_translate("Form", "9"))
        self.b7.setText(_translate("Form", "7"))
        self.b8.setText(_translate("Form", "8"))
        self.b9.setText(_translate("Form", "9"))
        self.bs.setText(_translate("Form", "Start\nRestart"))
        self.ll.setText(_translate("Form", "result..."))

    def start_game(self):
        self.ll.setText('lets start ,x or o')
        #restart
        ln=[self.l1,self.l2,self.l3,self.l4,self.l5,self.l6,self.l7,self.l8,self.l9]
        lbn = [self.b1, self.b2, self.b3, self.b4, self.b5, self.b6, self.b7, self.b8, self.b9]
        counter=1
        for i in ln:
            i.setText(f'{counter}')
            counter=counter+1
        for b in lbn:
            b.setEnabled(True)

    def click(self,bn):
        if bn.text()=='x':
            self.counter=0
            self.player1()
        elif bn.text()=='o':
            self.counter=1
            self.player1()
        elif bn.text()=='1':
            self.l1.setText(f'{self.player1()}')
            self.player2()
        elif bn.text()=='2':
            self.l2.setText(f'{self.player1()}')
            self.player2()
        elif bn.text()=='3':
            self.l3.setText(f'{self.player1()}')
            self.player2()
        elif bn.text()=='4':
            self.l4.setText(f'{self.player1()}')
            self.player2()
        elif bn.text()=='5':
            self.l5.setText(f'{self.player1()}')
            self.player2()
        elif bn.text()=='6':
            self.l6.setText(f'{self.player1()}')
            self.player2()
        elif bn.text()=='7':
            self.l7.setText(f'{self.player1()}')
            self.player2()
        elif bn.text()=='8':
            self.l8.setText(f'{self.player1()}')
            self.player2()
        elif bn.text()=='9':
            self.l9.setText(f'{self.player1()}')
            self.player2()
        self.winner_loser()

    def player1(self):
        self.ll.setText('your turn')
        if self.counter==0:
            return 'x'
        else:
            return 'o'

    def player2(self):
        lb = [self.l1, self.l2, self.l3, self.l4, self.l5, self.l6, self.l7, self.l8, self.l9]
        while True:
            cp = random.choice(lb)
            if cp.text()!='x' and cp.text()!='o':
                if self.player1()== 'x':
                    cp.setText('o')
                    break
                else:
                    cp.setText('x')
                    break
            else:
                continue
        self.ll.setText('now,your turn')

    def winner_loser(self):
        #radifi
        if self.l1.text()!='' and self.l2.text()==self.l1.text() and self.l3.text()==self.l1.text():
            self.ll.setText(f'{self.l1.text()} is winner')
            self.ghofl()
        elif self.l4.text()!='' and self.l5.text()==self.l4.text() and self.l6.text()==self.l4.text():
            self.ll.setText(f'{self.l4.text()} is winner')
            self.ghofl()
        elif self.l7.text()!='' and self.l8.text()==self.l7.text() and self.l9.text()==self.l7.text():
            self.ll.setText(f'{self.l7.text()} is winner')
            self.ghofl()
        #sotuni
        elif self.l1.text()!='' and self.l4.text()==self.l1.text() and self.l7.text()==self.l1.text():
            self.ll.setText(f'{self.l1.text()} is winner')
            self.ghofl()
        elif self.l2.text()!='' and self.l5.text()==self.l2.text() and self.l8.text()==self.l2.text():
            self.ll.setText(f'{self.l2.text()} is winner')
            self.ghofl()
        elif self.l3.text()!='' and self.l6.text()==self.l3.text() and self.l9.text()==self.l3.text():
            self.ll.setText(f'{self.l3.text()} is winner')
            self.ghofl()
        #ghotri
        elif self.l1.text()!='' and self.l5.text()==self.l1.text() and self.l9.text()==self.l1.text():
            self.ll.setText(f'{self.l1.text()} is winner')
            self.ghofl()
        elif self.l3.text()!='' and self.l5.text()==self.l3.text() and self.l7.text()==self.l3.text():
            self.ll.setText(f'{self.l3.text()} is winner')
            self.ghofl()

    def ghofl(self):
        lbn = [self.b1, self.b2, self.b3, self.b4, self.b5, self.b6, self.b7, self.b8, self.b9]
        for b in lbn:
            b.setEnabled(False)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
